### ISSUE TITLE
re-natal enable-source-maps broken?

### ISSUE THREAD

**Issue by gnl** [drapanjanas/re-natal#101]
With RN 0.42 I'm getting this:

```
% re-natal enable-source-maps
Patching react-native packager to serve *.map files
fs.js:583
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'node_modules/react-native/packager/react-packager/src/Server/index.js'
    at Object.fs.openSync (fs.js:583:18)
    at Object.fs.readFileSync (fs.js:490:33)
    at readFile (/usr/local/lib/node_modules/re-natal/re-natal.coffee:121:6)
    at edit (/usr/local/lib/node_modules/re-natal/re-natal.coffee:127:5)
    at patchReactNativePackager (/usr/local/lib/node_modules/re-natal/re-natal.coffee:326:3)
    at Command.<anonymous> (/usr/local/lib/node_modules/re-natal/re-natal.coffee:660:3)
    at Command.listener (/usr/local/lib/node_modules/re-natal/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:194:7)
    at Command.parseArgs (/usr/local/lib/node_modules/re-natal/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/re-natal/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/re-natal/re-natal.coffee:681:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/re-natal/re-natal.coffee:7:1)
    at Module._compile (module.js:571:32)
    at Object.loadFile (/usr/local/lib/node_modules/re-natal/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/usr/local/lib/node_modules/re-natal/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/re-natal/index.js:4:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3

command failed with status: 1
```

**Comment by drapanjanas** [comment]
Thanks! Looks like js file which we have to patch to serve *.map files, was moved. If it only this, fix is trivial.

**Comment by gnl** [comment]
Looking good, thanks!
