### ISSUE TITLE
Problem with java.xml.bind and Java 11

### ISSUE THREAD

**Issue by mfikes** [drapanjanas/re-natal#198]
```
$ re-natal --version
0.9.0
$ java -version
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28-201810021910)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11+28-201810021910, mixed mode)
$ re-natal init FooApp
Creating FooApp
☕  Grab a coffee! Downloading deps might take a while...
Creating Leiningen project
Updating Leiningen project
Creating React Native skeleton.
Creating Re-Natal config
Compiling ClojureScript
Command failed: lein prod-build
$ cd foo-app
$ lein prod-build
Compiling ClojureScript...
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found
Error encountered performing task 'cljsbuild' with profile(s): 'prod'
Subprocess failed
$ grep java.xml.bind project.clj
            :jvm-opts ["-XX:+IgnoreUnrecognizedVMOptions" "--add-modules=java.xml.bind"]
```

**Comment by mfikes** [comment]
If the `:jvm-opts` is instead replaced with `[]` (perhaps conditionally under JDK 11?), then another thing that would be needed is http-kit 2.3.0 in the mix, which nicely cleans things up via https://github.com/http-kit/http-kit/issues/356. In order to get this, we would want Figwheel 0.5.16 for https://github.com/bhauman/lein-figwheel/commit/6fb335961311bf172094cc05d392c40bbde66696 (we'd need to sort out #190)

**Comment by MarchLiu** [comment]
I has this problem too.
```
# lein with-profile +gorilla gorilla
Error encountered performing task 'gorilla' with profile(s): 'base,system,user,provided,dev,gorilla'
java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(org/httpkit/server.clj:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:
...
```
When JDK 11, javax.xml.bind module has been removed. If add this java options should get:

```
# lein with-profile +gorilla gorilla
Picked up _JAVA_OPTIONS: --add-modules=java.xml.bind
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found

```

 So we need a new way solve it.

**Comment by Jeel-Shah** [comment]
I had a similar problem. I was able to resolve the problem by following #228 which is to replace `=` by a space in 
`:jvm-opts ["-XX:+IgnoreUnrecognizedVMOptions" "--add-modules=java.xml.bind"]`.
