### ISSUE TITLE
RN 0.57.0 support problem with figwheel

### ISSUE THREAD

**Issue by vinurs** [drapanjanas/re-natal#202]
Hi,
   I create a project with 
  `re-natal init QnbApp`
  then, i update the react-native version to 0.57.0:
  `react-native-git-upgrade 0.57.0`
  and i want to develop with figwheel:
`re-natal use-ios-device simulator`
` re-natal use-figwheel`
`lein figwheel ios`
  `react-native run-ios`
but, the simulator shows this:

`
Loading dependency graph, done.
 BUNDLE  [ios, dev] ../../index.ios.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)::1 - - [27/Oct/2018:13:38:59 +0000] "GET /index.ios.bundle?platform=ios&dev=true&minify=false HTTP/1.1" 200 - "-" "QnbApp/1 CFNetwork/808.0.2 Darwin/18.0.0"
error: bundling failed: Error: Unable to resolve module `figwheel-bridge` from `/Users/vinurs/tmp/qnb-app/index.ios.js`: Module `figwheel-bridge` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/vinurs/tmp/qnb-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:209:1301)
    at ResolutionRequest.resolveDependency (/Users/vinurs/tmp/qnb-app/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:83:16)
    at DependencyGraph.resolveDependency (/Users/vinurs/tmp/qnb-app/node_modules/metro/src/node-haste/DependencyGraph.js:238:485)
    at Object.resolve (/Users/vinurs/tmp/qnb-app/node_modules/metro/src/lib/transformHelpers.js:180:25)
    at dependencies.map.result (/Users/vinurs/tmp/qnb-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:311:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/vinurs/tmp/qnb-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:307:16)
    at /Users/vinurs/tmp/qnb-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:164:33
    at Generator.next (<anonymous>)
    at step (/Users/vinurs/tmp/qnb-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:266:307)
 BUNDLE  [ios, dev] ../../index.ios.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)
`
I've done the step it promopt, but still failed

**Comment by phoenix2082** [comment]
In index.ios.js file. I have changed
require('figwheel-bridge')....

to 

require('./figwheel-bridge.js')

and able to get it working. After running 

$ react-native run-ios

I have closed simulator and Metro builder window before running above command.
