### ISSUE TITLE
Clojure 1.9.0-alpha11 breaks `lein prod-build`

### ISSUE THREAD

**Issue by KeatonDunsford** [drapanjanas/re-natal#63]
This is my first time posting an issue on Github, so hope I don't screw this up haha!

Just tried updating both my Clojure and ClojureScript dependencies in the project.clj of my new app project. Upgrading to the latest CLJS version 1.9.227 worked fine. When trying to go up from Clojure 1.9.0-alpha10 to 1.9.0-alpha11, I get the following massive error message:

```
Exception in thread "main" java.lang.IllegalArgumentException: Call to clojure.core/ns did not conform to spec:
In: [3 0] val: import fails spec: :clojure.core.specs/ns-refer-clojure at: [:args :clauses :refer-clojure :clause] predicate: #{:refer-clojure}
In: [3 0] val: import fails spec: :clojure.core.specs/ns-require at: [:args :clauses :require :clause] predicate: #{:require}
In: [3 0] val: import fails spec: :clojure.core.specs/ns-import at: [:args :clauses :import :clause] predicate: #{:import}
In: [3 0] val: import fails spec: :clojure.core.specs/ns-use at: [:args :clauses :use :clause] predicate: #{:use}
In: [3 0] val: import fails spec: :clojure.core.specs/ns-refer at: [:args :clauses :refer :clause] predicate: #{:refer}
In: [3 0] val: import fails spec: :clojure.core.specs/ns-load at: [:args :clauses :load :clause] predicate: #{:load}
In: [3 0] val: import fails spec: :clojure.core.specs/ns-gen-class at: [:args :clauses :gen-class :clause] predicate: #{:gen-class}
:clojure.spec/args  (cljsbuild.crossover (:use [clojure.java.io :only [as-url resource]]) (:require [cljsbuild.util :as util] [clojure.string :as string] [fs.core :as fs]) (import java.io.File java.net.URLDecoder))
, compiling:(cljsbuild/crossover.clj:1:1)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6795)
	at clojure.lang.Compiler.macroexpand(Compiler.java:6861)
	at clojure.lang.Compiler.eval(Compiler.java:6935)
	at clojure.lang.Compiler.load(Compiler.java:7403)
	at clojure.lang.RT.loadResourceScript(RT.java:374)
	at clojure.lang.RT.loadResourceScript(RT.java:365)
	at clojure.lang.RT.load(RT.java:455)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.core$load$fn__7645.invoke(core.clj:6008)
	at clojure.core$load.invokeStatic(core.clj:6007)
	at clojure.core$load.doInvoke(core.clj:5991)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5812)
	at clojure.core$load_one.invoke(core.clj:5807)
	at clojure.core$load_lib$fn__7590.invoke(core.clj:5852)
	at clojure.core$load_lib.invokeStatic(core.clj:5851)
	at clojure.core$load_lib.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5889)
	at clojure.core$load_libs.doInvoke(core.clj:5873)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5911)
	at clojure.core$require.doInvoke(core.clj:5911)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at user$eval15.invokeStatic(form-init2469899088480641630.clj:1)
	at user$eval15.invoke(form-init2469899088480641630.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6951)
	at clojure.lang.Compiler.eval(Compiler.java:6940)
	at clojure.lang.Compiler.load(Compiler.java:7403)
	at clojure.lang.Compiler.loadFile(Compiler.java:7341)
	at clojure.main$load_script.invokeStatic(main.clj:276)
	at clojure.main$init_opt.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invoke(main.clj:278)
	at clojure.main$initialize.invokeStatic(main.clj:309)
	at clojure.main$null_opt.invokeStatic(main.clj:343)
	at clojure.main$null_opt.invoke(main.clj:340)
	at clojure.main$main.invokeStatic(main.clj:422)
	at clojure.main$main.doInvoke(main.clj:385)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: Call to clojure.core/ns did not conform to spec:
In: [3 0] val: import fails spec: :clojure.core.specs/ns-refer-clojure at: [:args :clauses :refer-clojure :clause] predicate: #{:refer-clojure}
In: [3 0] val: import fails spec: :clojure.core.specs/ns-require at: [:args :clauses :require :clause] predicate: #{:require}
In: [3 0] val: import fails spec: :clojure.core.specs/ns-import at: [:args :clauses :import :clause] predicate: #{:import}
In: [3 0] val: import fails spec: :clojure.core.specs/ns-use at: [:args :clauses :use :clause] predicate: #{:use}
In: [3 0] val: import fails spec: :clojure.core.specs/ns-refer at: [:args :clauses :refer :clause] predicate: #{:refer}
In: [3 0] val: import fails spec: :clojure.core.specs/ns-load at: [:args :clauses :load :clause] predicate: #{:load}
In: [3 0] val: import fails spec: :clojure.core.specs/ns-gen-class at: [:args :clauses :gen-class :clause] predicate: #{:gen-class}
:clojure.spec/args  (cljsbuild.crossover (:use [clojure.java.io :only [as-url resource]]) (:require [cljsbuild.util :as util] [clojure.string :as string] [fs.core :as fs]) (import java.io.File java.net.URLDecoder))

	at clojure.spec$macroexpand_check.invokeStatic(spec.clj:627)
	at clojure.spec$macroexpand_check.invoke(spec.clj:616)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6789)
	... 42 more
Error encountered performing task 'cljsbuild' with profile(s): 'prod'
Subprocess failed
```

Obviously a lot being worked on and changed with Clojure.spec. Does anyone know specifically what change between alpha10 and alpha11 might be causing this?

Thanks!

**Comment by KeatonDunsford** [comment]
Nevermind, updating lein-cljsbuild to 1.1.4 in my dependencies fixed this. Thanks. :)
