### ISSUE TITLE
Problem getting started

### ISSUE THREAD

**Issue by ibarrick** [drapanjanas/re-natal#90]
I followed the directions in the readme and after `re-natal init TestApp` I get:

`Command failed: node -e "require('react-native/local-cli/cli').init('.', 'TestApp')"`

**Comment by drapanjanas** [comment]
Check if you have all [deps](https://github.com/drapanjanas/re-natal#dependencies) installed. 
If deps are fine, open terminal cd to `test-app` dir and try executing this command manually. The output might be telling what is the problem.

**Comment by TerjeNorderhaug** [comment]
I replicated the issue, then executed the failed command manually, resulting in the following:

> module.js:327
> Error: Cannot find module 'invariant'

**Comment by TerjeNorderhaug** [comment]
Fixed by upgrading npm to the latest version.

**Comment by aputs** [comment]
removing the space between ,'TestApp' works fine.
> `node -e "require('react-native/local-cli/cli').init('.','TestApp')"`

**Comment by dupuchba** [comment]
Same here but with `re-natal init WeatherProject -i om-next`
Can't understand why as the `re-natal init` worked yersteday.

**Comment by dupuchba** [comment]
@ibarrick have you found a solution

**Comment by dupuchba** [comment]
it might be something like this => https://github.com/facebook/react-native/issues/12542

**Comment by dupuchba** [comment]
working with facebook patch

**Comment by carocad** [comment]
I had the same problem. It is a react native bug: https://github.com/facebook/react-native/issues/11327

I solved it by globaly installing invariant: `npm install -g invariant`

**Comment by wilkerlucio** [comment]
I'm having the same issue, when I go inside and try to run the command I get:

```
Wilkers-MacBook-Pro:cook-clock wilkerlucio$ node -e "require('react-native/local-cli/cli').init('.','CookClock')"
/Users/wilkerlucio/Development/cook-clock/node_modules/metro-bundler/build/lib/TerminalClass.js:141
    this._nextStatusStr = util.format(format, ...args);
                                              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/wilkerlucio/Development/cook-clock/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/wilkerlucio/Development/cook-clock/node_modules/react-native/local-cli/server/runServer.js:18:18)
    at Module._compile (module.js:435:26)
```

I tried installing the `invariant` but that didn't helped =/

Any other alternatives to handle this?

**Comment by wilkerlucio** [comment]
Figure out, was my local node version, upgrading to `6.11.1` did the trick.

**Comment by teachtyler** [comment]
Bump

was working yesterday.. now getting same error initializing project


```
$ re-natal init FutureApp                                                                  
Creating FutureApp                                                                         
☕  Grab a coffee! I will use yarn, but fetching deps still takes time...                   
Creating Leiningen project                                                                 
Updating Leiningen project                                                                 
Creating React Native skeleton.                                                            
Command failed: node -e "require('react-native/local-cli/cli').init('.', 'FutureApp')"     
                                                                                           
SYSTEM@DESKTOP-0JIDQ0L c:\clojure\test                                                     
$ cd future-app                                                                            
                                                                                           
SYSTEM@DESKTOP-0JIDQ0L c:\clojure\test\future-app                                          
$ node -e "require('react-native/local-cli/cli').init('.', 'FutureApp')"                   
module.js:557                                                                              
    throw err;                                                                             
    ^                                                                                      
                                                                                           
Error: Cannot find module 'react-native/local-cli/cli'                                     
    at Function.Module._resolveFilename (module.js:555:15)                                 
    at Function.Module._load (module.js:482:25)                                            
    at Module.require (module.js:604:17)                                                   
    at require (internal/module.js:11:18)                                                  
    at [eval]:1:1                                                                          
    at Script.runInThisContext (vm.js:65:33)                                               
    at Object.runInThisContext (vm.js:199:38)                                              
    at Object.<anonymous> ([eval]-wrapper:6:22)                                            
    at Module._compile (module.js:660:30)                                                  
    at evalScript (bootstrap_node.js:474:27)                                               
```

## deps versions:

```
$ re-natal --version
0.8.0

$ lein -v
Leiningen 2.7.1 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM

$ watchman -v
4.9.1

$ react-native -v
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory

$ node -v
v9.4.0

$ npm -v
5.6.0
```

am on windows 10
